/* Name: Jerry He
 * Date: July 25
 * Assignment Name: Culminating Task
 * Purpose: To create a program that prompts the user for an integer between 1-100, validates
 * the data information, and compares this value to a randomly generated integer
 * while repeating this process until the user either guesses it, or runs out 
 * of attempts
 *
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jerry He
 */
public class CulminatingTask extends javax.swing.JFrame {

    /**
     * Creates new form CulminatingTask
     */
    
    public CulminatingTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        lblInstructionsOne = new javax.swing.JLabel();
        btnCheckUserInput = new javax.swing.JButton();
        lblNumGuesses = new javax.swing.JLabel();
        lblGuessMessage = new javax.swing.JLabel();
        lblGuessCounter = new javax.swing.JLabel();
        lblGuessConfirmation = new javax.swing.JLabel();
        lblImageOne = new javax.swing.JLabel();
        lblImageTwo = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JButton();
        lblResults = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblAllGuesses = new javax.swing.JLabel();
        lblInstructionsTwo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Caveat", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Number Guesser");

        txtUserGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserGuessActionPerformed(evt);
            }
        });

        lblInstructionsOne.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblInstructionsOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructionsOne.setText("Enter an integer between 1-100. The program will tell you if the random number is higher or lower than you guess.");

        btnCheckUserInput.setText("Check Number");
        btnCheckUserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUserInputActionPerformed(evt);
            }
        });

        lblNumGuesses.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lblNumGuesses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumGuesses.setText("0");

        lblGuessMessage.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lblGuessMessage.setText("Your Guess Was:");

        lblGuessCounter.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lblGuessCounter.setText("Guess Counter:");

        lblGuessConfirmation.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        lblGuessConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuessConfirmation.setText("...");

        lblImageOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuestionMarks.png"))); // NOI18N

        lblImageTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Thinking.png"))); // NOI18N

        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        lblResults.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        lblResults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblAllGuesses.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblAllGuesses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllGuesses.setText("All Guesses will be Displayed Here");

        lblInstructionsTwo.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblInstructionsTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructionsTwo.setText("You Only Have 10 Guesses. Play Smart!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblGuessCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(lblNumGuesses, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblGuessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblGuessConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnCheckUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImageTwo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnExit)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblImageOne)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAllGuesses, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblInstructionsOne, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                            .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInstructionsTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstructionsOne)
                .addGap(1, 1, 1)
                .addComponent(lblInstructionsTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblImageTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCheckUserInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGuessMessage)
                            .addComponent(lblGuessConfirmation))
                        .addGap(49, 49, 49)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGuessCounter)
                    .addComponent(lblNumGuesses))
                .addGap(43, 43, 43)
                .addComponent(lblResults)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImageOne))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblAllGuesses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit)
                            .addComponent(btnPlayAgain))
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        // TODO add your handling code here:
        gameReset();
    }//GEN-LAST:event_btnPlayAgainActionPerformed
    
    private void btnCheckUserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUserInputActionPerformed
        // TODO add your handling code here:
        //Declaration of Variables
        int intUserGuess = 0;
       
        //Call intUserGuess function to accept user input and verify data
        intUserGuess = verifyNumber()[0];
        
        //Check if the guess is valid
        if (intUserGuess >= 1 && intUserGuess <= 100)
        {
            //Call the playGame function to start the guessing game
            playGame(intUserGuess, numberSaved);
        }
    }//GEN-LAST:event_btnCheckUserInputActionPerformed

    private void txtUserGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserGuessActionPerformed

    //METHOD DEFINITIONS
   
    //Permanently saving the randomized number
    private static int numberSaved = randomNumber();
    
    //Saving a guess counter so it does not reset in the function
    private static int guessCount = 0;
    
    //Creating a permanent array to hold all the guesses the user makes
    private static int [] guessesArray = new int [11];
    
    /*
    Method Name: randomNumber
    Description: This function randomizes an integer between 1-100 and stores
    it into an array
    Parameter Type: void
    Return Type: int
    */
    private static int randomNumber()
    {
        //Declaration of variables
        final int INT_MAX_NUM = 100;
        int intTargetNum []  = new int [1]; 
        
        //Randomizing an integer between 1 and 100
        numberSaved = (int)Math.round(Math.random()*(INT_MAX_NUM-1)+1);
        
        return numberSaved;
    
    }
    /*
    Method Name: verifyNumber
    Description: This function checks if the user's input is invalid, such as
    a non-integer, or if it is an integer outside of the range of 1-100.
    Parameter Type: void
    Return Type: array int
    */
    private int [] verifyNumber()
    {
        //Declaration of variables
        final int INT_MAX_NUM = 100;
        final int INT_MIN_NUM = 1;
        String strTempGuess = "";
        int intInputValue = 0;
        int intUserGuess[] = new int[1];
            
        //Save user input as a string to verify later
        strTempGuess = txtUserGuess.getText();

        //Check if the user entered an integer
        try 
        {
            //Try to turn user input into an integer
            intInputValue = Integer.parseInt(strTempGuess);
            
            //Check if the user entered an integer within the range
            if (intInputValue >= INT_MIN_NUM && intInputValue <= INT_MAX_NUM)
            {
                //Save the user's guess into an array
                intUserGuess[0] = intInputValue;
            } 
            //User did not enter an integer within the range
            else 
            {
                //Output message to user that input was not within the range
                lblGuessConfirmation.setText("Not a value between 1-100");
            }
        } 
        //User did not enter an integer
        catch (NumberFormatException e) 
        {
            //Output message to user that input is invalid
            lblGuessConfirmation.setText("Invalid Value Type");
        }
    return intUserGuess;  
    }
    
    /*
    Method Name: playGame
    Description: This function compares the user's guess to the random number
    generated by the computer and outputs a message depending on results of the 
    comparison and counts the number of guesses
    Parameter Type: int
    Return Type: void
    */
    private void playGame(int intUserGuess, int intComputerNumber)
    {
        //Declaration of variables
        final int INT_MAX_TRIES = 10;
        String strFinalMessage = "";
        
        //Check if the user's guess was equal to the random number
        if (intUserGuess == intComputerNumber)
        {
            //Output a congratulatory message
            lblGuessConfirmation.setText("Correct Guess!");
            lblResults.setText("Congratulations! You guessed correctly!");
        }
        //Check if the user's guess was greater than the random number
        else if (intUserGuess > intComputerNumber)
        {
            //Output a message to tell the user the guess was too high
            lblGuessConfirmation.setText("Guess is too high!");   
        }
        //The user input a number smaller than the random number
        else 
        {
            //Output a message to tell the user the guess was too low
            lblGuessConfirmation.setText("Guess is too low!"); 
        }
        //Increase the counter of guesses after every button click
        guessCount++;

        //Output the number of guesses to the user
        lblNumGuesses.setText(String.valueOf(guessCount));
        
        //Save every user guess to an array
        guessesArray[guessCount] = intUserGuess;
        
        //Check if the game has ended
        if (guessCount == INT_MAX_TRIES || intUserGuess == intComputerNumber)
        {
            //Hiding the check number button that continues the game
            btnCheckUserInput.setVisible(false);
            //Loop to output all user responses
            for (int i = 1; i <= guessCount; i++)
            {
                strFinalMessage += " " + guessesArray[i] + " "; 
            }
            //Outputs all the guesses made
            lblAllGuesses.setText(strFinalMessage);
        }
        
        //Check if the user did not guess the number within 10 tries
        if (guessCount == INT_MAX_TRIES && intUserGuess != intComputerNumber)
        {
            //Output a message and the random number they could not guess
            lblResults.setText("You Couldn't Guess it in 10 tries! The number "
                    + "was " + intComputerNumber + ".");
        }
        
    }
    /*
    Method Name: gameReset
    Description: This function resets all the values to restart the game
    Parameter Type: void
    Return Type: void
    */
    private void gameReset()
    {
        //Generating a new random number
        randomNumber();
        
        //Resetting all the information and data from the previous game
        guessCount = 0;
        lblNumGuesses.setText(String.valueOf(guessCount));
        lblGuessConfirmation.setText("...");
        btnCheckUserInput.setVisible(true);
        lblAllGuesses.setText("All Guesses Will Be Displayed Here");
        lblResults.setText(null);
    }
            
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CulminatingTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CulminatingTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CulminatingTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CulminatingTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CulminatingTask().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckUserInput;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAllGuesses;
    private javax.swing.JLabel lblGuessConfirmation;
    private javax.swing.JLabel lblGuessCounter;
    private javax.swing.JLabel lblGuessMessage;
    private javax.swing.JLabel lblImageOne;
    private javax.swing.JLabel lblImageTwo;
    private javax.swing.JLabel lblInstructionsOne;
    private javax.swing.JLabel lblInstructionsTwo;
    private javax.swing.JLabel lblNumGuesses;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
